


dataset_path: /home/student/Desktop/Groundeep/stimuli_dataset_10_10
dataset_name: stimuli_dataset.npz
output_root: results/analysis
val_size: 0.10
use_wandb: true
wandb_project: numerosity-offline
seed: 42
anchor: 0

model_to_analyze:
  - arch: iDBN_1500_500
    distribution: uniform
    model_uniform: /home/student/Desktop/Groundeep/networks/uniform/idbn_new_dataset_200_epochs_i_dbn_trained_uniform_1500_500.pkl
    model_zipfian: artifacts/checkpoints/idbn_zipf.pkl
    val_size: 0.05
